/**
 * 在 state 更新完成和 listener 被通知之后发送崩溃报告。
 */

const crashReporter = store => next => action => {
  try {
    return next(action)
  } catch (err) {
    console.error('Caught an exception!', err)
    Raven.captureException(err, {
      extra: {
        action,
        state: store.getState()
      }
    })
    throw err
  }
}

export default crashReporter;
